version: '2'
services:
    calibre-web:
        image: linuxserver/calibre-web
        container_name: calibre-web
        restart: always
        ports:
            - 8083:8083
        volumes:
            - ./books:/books
        environment:
            - PGID=65539
            - PUID=1029

